### ISSUE TITLE
Wiki improvements, 5th-6th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#162]
**DESCRIPTION:**
Wiki's content needs to be reviewed, organised and improved.

**DEADLINE:**  5th-6th April

**TO DO**:
- [x] Fix development_farming branch: https://github.com/threefoldfoundation/info_foundation_archive/pull/403 (@andhartl ?)
- [x] All issues we want to resolve before casper : https://github.com/threefoldfoundation/home/issues/155 (@Sacha96) 
- [x] Get Started, SDK manual: https://github.com/threefoldfoundation/info_sdk/issues/319 (@xmonader @weynandkuijpers @gmachtel)
- [x] Rework Architecture sections: https://github.com/threefoldfoundation/home/issues/92 (@despiegk @weynandkuijpers @gmachtel)
- [x] Vesting explained: https://github.com/threefoldfoundation/info_foundation_archive/issues/401 (@Sacha96)
- [x] Fix wiki navbar: https://github.com/threefoldfoundation/info_foundation_archive/issues/406 (@Hamdy)
- [x] Development Tokens: https://github.com/threefoldfoundation/info_foundation_archive/pull/408 (@despiegk)
- [x] tokonomics 3 on wiki: https://github.com/threefoldfoundation/info_foundation_archive/issues/410 (@despiegk)

**Comment by Sacha96** [comment]
Cleared #155 to a max, rest is on @despiegk as I don't have info

**Comment by Sacha96** [comment]
@gmachtel got a good start with SDK, I know have to review it (new issue for 2.8.1). Also checked decentralization status and this was updated by @despiegk. So this issue can be closed.
