### ISSUE TITLE
Web Casper release, 7th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#163]
**DESCRIPTION:**
There are urgent updates across our websites needed before 7th April due to releasing Casper announcement.

**DEADLINE:**  7th April

**TO DO**:
- [x] Partners needs to be good enough: https://github.com/threefoldfoundation/data_threefold/issues/31 (@samtaggart)
- [x] Add Casper to apps page: https://github.com/threefoldfoundation/www_threefold_marketplace/issues/34 (@samtaggart @Vilnite)
- [x] Update homepage partners: https://github.com/threefoldfoundation/www_threefold_io/issues/42 (@samtaggart @Vilnite)
- [x] Casper announcement: https://github.com/threefoldfoundation/home_private/issues/19 (@samtaggart)
- [x] Prepare Casper page: https://github.com/threefoldfoundation/data_threefold/issues/27 (@samtaggart @BenjellounO)
- [x] Add Casper app to page marketplace: https://github.com/threefoldfoundation/www_threefold_marketplace/issues/33 (@samtaggart @BenjellounO)
- [x] Update TFT listings: https://github.com/threefoldfoundation/home/issues/160 (@samtaggart @BenjellounO) *sent on our side, Benje will push them tomorrow AM*
- [x] Add Casper to VDC: https://github.com/threefoldtech/js-sdk/issues/2874 (@samtaggart) *issue created, to be added tomorrow, confirmed with Thabet*
- [x] Show TFT on Interstellar: https://github.com/threefoldfoundation/home/issues/157 (@samtaggart) *seems to be fixed, waiting on K / Nickolay*

**Comment by Sacha96** [comment]
Partners is done, casper announcement is ready we will coordinate accordingly and TFT is live on stellar. Closing the issue
