### ISSUE TITLE
All web presence 2.8 release, 11th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#164]
**DESCRIPTION:**
Weekly sprint updates for all web presence.

**DEADLINE:**  11th April

**TO DO**:
- [x] Footer added for DT: https://github.com/threefoldfoundation/www_threefold_twin/issues/57 (@Sacha96 @AlexandreHannelas)
- [x] Rework hardcoded image sections: https://github.com/threefoldfoundation/www_threefold_io/issues/59 (@Vilnite)
- [x] Make sure Ranking works: https://github.com/threefoldfoundation/data_threefold/issues/30 (@Hamdy)
- [x] Fix mobile responsiveness for all websites: https://github.com/threefoldfoundation/home/issues/146 (@ehab-hassan)
_In Progress - will be finished first thing on next sprint_
- [x] Integrate VDC on marketplace: https://github.com/threefoldfoundation/www_threefold_marketplace/issues/28 (@samtaggart @Sacha96)
- [x] Make sure liquidity page is accurate (on wiki): https://github.com/threefoldfoundation/info_threefold/issues/9 (@Sacha96)
- [x] Review DT wiki: https://github.com/threefoldfoundation/www_threefold_twin/issues/51 (@Sacha96)
- [x] Update image on DT experience page: https://github.com/threefoldfoundation/www_threefold_twin/issues/64 (@Vilnite)
- [x] Correct TFTA definition on wiki: https://github.com/threefoldfoundation/home/issues/159 (@Sacha96 @samtaggart)
- [x] take down threefold.me: https://github.com/threefoldfoundation/home/issues/148 (@Hamdy @Pishoy)

**Comment by Sacha96** [comment]
So here's my take on some of the above issues. 

- #111 I will align with @VonSub tomorrow to know where this is at as this should be the highest priority for websites to track visitors and gather data before further edits!!!
- #140 @samtaggart will cover this today and then assign @samaradel .
- #146 i guess @ehab-hassan  is going through this today or this week - this is quite important actually. 
-  threefoldfoundation/www_threefold_io#33 we will discuss with amazix before deleting @samtaggart will look at this this week. 

Let's bring them to 2.8.1. 

For the rest of them need to get in touch with.

**Comment by Vilnite** [comment]
Some of the issues we didn't have time for on this sprint so the are moved to next one.
Note for future planning: we put way too many issues on one sprint, need to be more mindful about time and resources we have, only focusing on priority issues, leaving "good to have" ones in team projects to be worked on if time allows.
