### ISSUE TITLE
web_2.7.3 release, 18th April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#168]
**DESCRIPTION:**
"Weekly web presence update and release on Sunday, 18th April."

**DEADLINE:** 18th April

**TO DO:**
- [x] Analytics added to all websites, https://github.com/threefoldfoundation/home/issues/111 (@VonSub, @ehab-hassan)
- [x] Fixed mobile responsiveness for all websites, https://github.com/threefoldfoundation/home/issues/146 (@ehab-hassan)
- [x] Metadata for all websites sent to Samar https://github.com/threefoldfoundation/home/issues/140 (@samtaggart)
- [x] Metadata updated by Samar https://github.com/threefoldfoundation/home/issues/170 (@samaradel)
- [x] Change mentions of Team to People, https://github.com/threefoldfoundation/home/issues/151 (@samaradel)
- [x] Address Partner content, https://github.com/threefoldfoundation/data_threefold/issues/32 (@Vilnite, @samaradel)
- [x] Move Grid block from 3Node to Tech, https://github.com/threefoldfoundation/www_threefold_farming/issues/90 (@Vilnite)
- [x]  Review Publisher content, https://github.com/threefoldfoundation/www_threefold_marketplace/issues/27 (@Vilnite)
- [x] SDK Manual, https://github.com/threefoldfoundation/info_sdk/issues/319 (@gmachtel, @weynandkuijpers, @xmonader)
- [x] TDE cleanup on wiki, https://github.com/threefoldfoundation/home/issues/101 (@Sacha96, @despiegk)
- [x] Cloud wiki full review https://github.com/threefoldfoundation/info_cloud/issues/14 (@Sacha96). Sections Reviewed/created:
> - [x] ReadMe
> - [x] P2P Cloud Section (New section to be created)
> - [x] eVDC
> - [x] Kubernetes
