### ISSUE TITLE
web_2.7.4, 23rd April

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#175]
**DESCRIPTION:**
- Adding Carbon Neutral positioning on wiki and linking to websites
- Overal website updates
- Overal wiki updates

**DEADLINE:** 23rd April

**TO DO:**
- [x] Add Open Graph Tags, https://github.com/threefoldfoundation/home/issues/172, (@Hamdy )
_to be addressed when @Hamdy is back_
- [x] Edit token page, https://github.com/threefoldfoundation/www_threefold_io/issues/66 (@samaradel )
- [x] Carbon Neutral page on wiki, https://github.com/threefoldfoundation/info_cloud/issues/12 (@Sacha96 )
- [x] navigation update for websites, https://github.com/threefoldfoundation/home/issues/176 (@Vilnite )

**Comment by Sacha96** [comment]
Finally we're holding with carbon neutral for now so that we go live with full fledged details for announcement
