### ISSUE TITLE
documentation todos

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#178]
- [ ] TOKENSTATS- document the api calls on a wiki page on main wiki @gmachtel 

- [x] TF Connect Wallet : document the btc implementation __done__ but need to redo screenshots once on mainnet (as now 'staging is mentioned'

- [ ] [testplan 2.7.1](https://github.com/threefoldtech/home/issues/1040) should be made visible on cloud wiki

- [x] [bsc bridge tutorial ](https://github.com/threefoldtech/binance-chain-bridge-dapp/issues/1)

- [ ] [SDK Manual - documentation: show how to use evdc etcd for QSFS config ](https://github.com/threefoldtech/binance-chain-bridge-dapp/issues/1) : __To do__ but given changes in architecture (no etcd anymore ?) not priority
