### ISSUE TITLE
TFT

### ISSUE THREAD

**Issue by Vilnite** [threefoldfoundation/home#183]
**Description:**
The goal is to increase liquidity for TFT and fund Foundation ecosystem support and growth activities through OTC sales.

**To Do:**

- [ ] We improve the listing situation on [coinmarketcap, coingecko](https://github.com/threefoldfoundation/home_private/issues/142) and[ livecoinwatch ]( https://github.com/threefoldfoundation/home_private/issues/141)

- [ ] Through influencers, we intend to spread the word around ThreeFold. This converts into TFT purchases.
https://github.com/threefoldfoundation/home_private/issues/61 & https://github.com/threefoldfoundation/home_private/issues/143

- [ ] https://github.com/threefoldfoundation/home_private/issues/131 & 

- [ ] Get TFT promoted in Korea https://github.com/threefoldfoundation/home_private/issues/78

- [ ] Improve the visibility and liquidity situation for TFT on pancakeswap though working towards getting a farm for a TFT pair.
https://github.com/threefoldfoundation/home_private/issues/137

- [ ] Partnerships or Grants from [Polkadot](https://github.com/threefoldfoundation/home_private/issues/59
) or Cardano. I am following an angle regarding Cardano at the moment and will create an issue once it looks promising.

- [ ] We are engaged in community growth activities in India with the help of Gaurav Gupta. The intention is to have his colleague Rachna manage PR, local community chat & social channels for ThreeFold. At the moment we are waiting for a publication from CyberMedia. https://github.com/threefoldfoundation/home_private/issues/86

- [ ] https://github.com/threefoldfoundation/home_private/issues/52

- [ ] We are pitching the announcement with DGB to journalists. The intended outcome is one or multiple publications in A tier media https://github.com/threefoldfoundation/home_private/issues/58

- [ ] AMAs in the week of 17th of May with these channels: AMAlovers club, Satoshistreetbets and BSC daily.

- [ ] We continue the preparations around carbon-neutral NFTs. https://github.com/threefoldfoundation/home_private/issues/51

- [ ] Working on a 3-month budget to outline the PR & influencer activities. https://github.com/threefoldfoundation/home_private/issues/108

- [ ] Coordinating the TF presence, booth and speaker slot on AIBC https://github.com/threefoldfoundation/home_private/issues/151

- [ ] Handle TFT OTC requests from our network.

**Deliverable:**
Liquidity on TFT & OTC sales.
Please note that most of the To-dos depend on external decisions.

**Deadline:**
31st May

**Comment by Vilnite** [comment]
please see: https://github.com/threefoldfoundation/promotion/issues/152
