### ISSUE TITLE
ThreeFold x Owncloud Launch

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldfoundation/home#219]
[Team Promotion story on circle](https://circles.threefold.me/project/team_onboarding/us/29?kanban-status=1986)

ThreeFold has teamed up with Owncloud to provide a time-limited freemium experience of Owncloud product on the TFGrid as a SaaS product. Users would soon be able to deploy their freemium TF Owncloud solution by signing up for an account on the new TF Owncloud deployer website using their TFConnect SSO (ThreeFold ID).

This story requires both marketing- and product development teams' work, the goal is to launch the product successfully.
Launch Preparation

- [x] [ThreeFold Owncloud Deployer](https://github.com/threefoldtech/home/issues/1151) @xmonader 
- [x] [ThreeFold Owncloud Admin Dashboard](https://github.com/threefoldtech/home/issues/1151) @xmonader 
- [ ] [Terms and Conditions](https://github.com/threefoldtech/home/issues/1151) @weynandkuijpers 
- [ ] IPs and capacity @christopherhutton 
- [ ] check if Yggdrasil is good enough to support the launch @ramezsaeed 
- [ ] QA validation greenlight @ramezsaeed @rkhamis 
- [ ] Owncloud Knowledge onboarding for Support @sabrinasadik 
- [ ] Documentation @xmonader @rkhamis 
- [ ] Internal Launch Announcement / Press Release @HannahCordes @sasha-astiadi 
- [ ] External Marketing / Promotion @christopherhutton

**Comment by sasha-astiadi** [comment]
Dev team (Alpha 6 launch) is blocked because of this project, we do not know of whether launch owncloud as a part of Alpha-6, or not... terms condition missing @christopherhutton @weynandkuijpers

**Comment by sasha-astiadi** [comment]
missing terms and conditions

**Comment by sabrinasadik** [comment]
Project is off the table, closing issues.
