### ISSUE TITLE
checklist TF Event

### ISSUE THREAD

**Issue by despiegk** [threefoldfoundation/home#51]
- [x] website event on github ???
    - [ ] website is autopublished on our web infra
- [x] contactlist with hosts/guests
     - [ ] link contact list with registration form
- [x] make sure that coordinators know what they are expected to do
- [x] hosts need to go to their audience: its 200 for paying ones, we can say because of sponsoring  its no more
     - [ ] need to get more people who matter
- [ ] better teaser around decentralization (3bot...) (kristof)
- [x] agenda (kristof)
- [x] is there an email list or chat group for everyone coming?

**Comment by Sacha96** [comment]
@despiegk I believe the above points are covered, therefore I'm closing the issue
