### ISSUE TITLE
ACI website reboot

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/home#60]
- [x] [design source ](https://github.com/threefoldfoundation/home/issues/61)
- [x] [technical decisions](https://github.com/threefoldfoundation/www_threefold_ecosystem/issues/39)
- [ ] [convert design to the template](https://github.com/threefoldfoundation/www_threefold_ecosystem/issues/40) (or redone using pingendo) (no way back after this move when we start integration with svelte)
- [ ] [integrate with svelte](https://github.com/threefoldfoundation/www_threefold_ecosystem/issues/41)
- [ ] [update infrastructure staging, production](https://github.com/threefoldfoundation/www_threefold_ecosystem/issues/42)
