### ISSUE TITLE
Get Community website live

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/home#63]
- [x] [ranking for circles](https://github.com/threefoldfoundation/www_ambassadors/issues/2) 
- [x] [values page](https://github.com/threefoldfoundation/www_ambassadors/issues/5)
- [x] [home page](https://github.com/threefoldfoundation/www_ambassadors/issues/4)
- [x] [should only show ambassadors](https://github.com/threefoldfoundation/www_ambassadors/issues/3)
- [x] [new content for home page](https://github.com/threefoldfoundation/www_community/issues/14)
